export const RECEIVE_RATES = 'RECEIVE_RATES';

export const SUBMIT_OPTION_FROM = 'SUBMIT_OPTION_FROM';
export const SUBMIT_OPTION_TO = 'SUBMIT_OPTION_TO';

export const UPDATE_OPTION_FROM = 'UPDATE_OPTION_FROM';
export const UPDATE_OPTION_TO = 'UPDATE_OPTION_TO';
